version: "2"
services:
  mvp:
    build: .
    ports:
      - 80:3000
    environment:
      - MONGODB=mongodb://eperiou:eperiou@mongo:27017
      - PORT=3000
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eperiou
      - MONGO_INITDB_ROOT_PASSWORD=eperiou
